### ISSUE TITLE
Mangles this snes header patch somehow

### ISSUE THREAD

**Issue by i30817** [heuripedes/ipsbehead#1]
http://www.romhacking.net/hacks/2744/ (click on download and open the archive for the ips)

if you apply ipsbehead to 'LtFoD_Restored_v2-4.ips' (crc `39924650`) you end up with a file that doesn't boot in softpatching applied to the version of the rom without a header.

patch file crc after 'behead': `0a48bf96`

If you apply a header with nsrt (or similar) hardpatch the rom, remove the header and then create a new ips (i used flips) you end with a file `caf15894`.

This is the first bug i've ever found in this software after years of using it for snes and pce hacks.

**Comment by i30817** [comment]
This comment might help:
http://www.romhacking.net/forum/index.php?topic=23307.msg364050#msg364050

**Comment by heuripedes** [comment]
Released an updated version.
